<?php

namespace Container2I5fSWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X5wiI3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X_5wiI3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X_5wiI3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'smRepo' => ['privates', 'App\\Repository\\SocialMediaRepository', 'getSocialMediaRepositoryService', true],
        ], [
            'em' => '?',
            'smRepo' => 'App\\Repository\\SocialMediaRepository',
        ]);
    }
}
