<?php

namespace Container2I5fSWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AzHTDsTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AzHTDsT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AzHTDsT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'socialMedia' => ['privates', '.errored..service_locator.AzHTDsT.App\\Entity\\SocialMedia', NULL, 'Cannot autowire service ".service_locator.AzHTDsT": it needs an instance of "App\\Entity\\SocialMedia" but this type has been excluded in "config/services.yaml".'],
        ], [
            'socialMedia' => 'App\\Entity\\SocialMedia',
        ]);
    }
}
