<?php

namespace Container2I5fSWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Cvvzvb5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cvvzvb5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cvvzvb5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reservationTransport' => ['privates', '.errored..service_locator.cvvzvb5.App\\Entity\\ReservationTransport', NULL, 'Cannot autowire service ".service_locator.cvvzvb5": it needs an instance of "App\\Entity\\ReservationTransport" but this type has been excluded in "config/services.yaml".'],
            'stationRepository' => ['privates', 'App\\Repository\\StationRepository', 'getStationRepositoryService', true],
        ], [
            'entityManager' => '?',
            'reservationTransport' => 'App\\Entity\\ReservationTransport',
            'stationRepository' => 'App\\Repository\\StationRepository',
        ]);
    }
}
