<?php

namespace Container2I5fSWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WxzU4dOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wxzU4dO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wxzU4dO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservation' => ['privates', '.errored..service_locator.wxzU4dO.App\\Entity\\ReservationTransport', NULL, 'Cannot autowire service ".service_locator.wxzU4dO": it needs an instance of "App\\Entity\\ReservationTransport" but this type has been excluded in "config/services.yaml".'],
        ], [
            'reservation' => 'App\\Entity\\ReservationTransport',
        ]);
    }
}
