<?php

namespace Container2I5fSWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WtTOPxFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WtTOPxF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WtTOPxF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservationTransportRepository' => ['privates', 'App\\Repository\\ReservationTransportRepository', 'getReservationTransportRepositoryService', true],
        ], [
            'reservationTransportRepository' => 'App\\Repository\\ReservationTransportRepository',
        ]);
    }
}
