<?php

namespace Container2I5fSWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationTransport4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wxzU4dO.App\Entity\ReservationTransport' shared service.
     *
     * @return \App\Entity\ReservationTransport
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.wxzU4dO": it needs an instance of "App\\Entity\\ReservationTransport" but this type has been excluded in "config/services.yaml".');
    }
}
