<?php

namespace Container2I5fSWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSocialMedia2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hvt4Me9.App\Entity\SocialMedia' shared service.
     *
     * @return \App\Entity\SocialMedia
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hvt4Me9": it needs an instance of "App\\Entity\\SocialMedia" but this type has been excluded in "config/services.yaml".');
    }
}
