<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4MPHi6f\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4MPHi6f/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4MPHi6f.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4MPHi6f\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4MPHi6f\App_KernelDevDebugContainer([
    'container.build_hash' => '4MPHi6f',
    'container.build_id' => '777f560e',
    'container.build_time' => 1744714687,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4MPHi6f');
