<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAapJ8iZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAapJ8iZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAapJ8iZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAapJ8iZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAapJ8iZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'AapJ8iZ',
    'container.build_id' => 'b2a7bbaa',
    'container.build_time' => 1744713986,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAapJ8iZ');
