<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKURrgHw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKURrgHw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKURrgHw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKURrgHw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKURrgHw\App_KernelDevDebugContainer([
    'container.build_hash' => 'KURrgHw',
    'container.build_id' => '8e0d45e2',
    'container.build_time' => 1744658049,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKURrgHw');
